name: Generate Snake

on:
  workflow_dispatch:   # Allows manual triggering
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Upload snake.svg as artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake-svg
          path: dist/snake.svg
